import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Royal Class",
  description: "Generated by create next app",
};
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "600", "700"], // Specify the weights you want to use
  subsets: ["latin"], // Specify the subsets you need
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
